//! systemd backend for the monitor: unit file + `systemctl` (helpers in `nettest_service`).
//!
//! The unit always grants CAP_NET_RAW: ICMP ping sockets usually work without it, but the
//! raw-socket fallback needs it, and a `ping://` target added to the config later must not
//! silently become "permanently down".

use std::path::PathBuf;
use std::process::ExitCode;

use nettest_service::files::{copy_binary, remove_binary};
use nettest_service::linux::{
    active_state, install_unit, remove_unit, require_systemd, status_text, systemctl,
};
use nettest_service::systemd::{UnitSpec, render_unit};

use super::{
    DESCRIPTION, InstallArgs, Report, SERVICE_NAME, ServiceError, describe, installed_config,
    purge_files, service_paths, stage_config,
};

fn unit_text(exec: &std::path::Path, paths: &super::ServicePaths) -> String {
    let exec_start = format!(
        "{} monitor --config %d/monitor.toml --log-file {}",
        exec.display(),
        paths.log_file.display()
    );
    render_unit(&UnitSpec {
        header: &[
            "Generated by `nettest-client service install`. Settings live in /etc/nettest/monitor.toml;",
            "after editing it run `nettest-client service restart` (or re-run `service install --from`).",
        ],
        description: DESCRIPTION,
        documentation: "man:nettest-client",
        exec_start: &exec_start,
        credential: ("monitor.toml", &paths.config),
        state_dir: None,
        logs_dir: "nettest-monitor",
        restart_sec: 5,
        capabilities: &["CAP_NET_RAW"],
    })
}

fn report_state(out: &mut Report, resolved: &super::Resolved) {
    let paths = service_paths();
    out.line(format!(
        "service     {SERVICE_NAME}.service: {}",
        active_state(SERVICE_NAME)
    ));
    for l in describe(resolved, &paths) {
        out.line(l);
    }
    out.line(format!(
        "logs        journalctl -u {SERVICE_NAME}  (also {})",
        paths.log_file.display()
    ));
}

pub fn install(a: InstallArgs, out: &mut Report) -> Result<(), ServiceError> {
    require_systemd()?;
    let paths = service_paths();
    let resolved = stage_config(a.from.as_deref(), &paths, out)?;
    let exec = if a.no_copy {
        std::env::current_exe()?
    } else {
        copy_binary(&paths.bin)?
    };
    install_unit(&paths.unit, &unit_text(&exec, &paths), SERVICE_NAME)?;
    std::thread::sleep(std::time::Duration::from_millis(700));
    out.line(format!(
        "installed   {} (exec {})",
        paths.unit.display(),
        exec.display()
    ));
    report_state(out, &resolved);
    out.line("edit        change /etc/nettest/monitor.toml then `nettest-client service restart`");
    Ok(())
}

pub fn uninstall(purge: bool, out: &mut Report) -> Result<(), ServiceError> {
    require_systemd()?;
    let paths = service_paths();
    if remove_unit(&paths.unit, SERVICE_NAME)? {
        out.line(format!("removed     {}", paths.unit.display()));
    } else {
        out.line("service was not installed");
    }
    if remove_binary(&paths.bin, 1)? {
        out.line(format!("removed     {}", paths.bin.display()));
    }
    if purge {
        purge_files(&paths, out)?;
    } else {
        out.line(format!(
            "kept        {} and {} (use --purge to delete)",
            paths.config.display(),
            paths.log_file.display()
        ));
    }
    Ok(())
}

pub fn start(out: &mut Report) -> Result<(), ServiceError> {
    require_systemd()?;
    systemctl(&["start", SERVICE_NAME])?;
    out.line(format!("{SERVICE_NAME}: {}", active_state(SERVICE_NAME)));
    Ok(())
}

pub fn stop(out: &mut Report) -> Result<(), ServiceError> {
    require_systemd()?;
    systemctl(&["stop", SERVICE_NAME])?;
    out.line(format!("{SERVICE_NAME}: {}", active_state(SERVICE_NAME)));
    Ok(())
}

pub fn restart(out: &mut Report) -> Result<(), ServiceError> {
    require_systemd()?;
    let paths = service_paths();
    // Catch a broken edit before systemd loops on it.
    if let Err(e) = installed_config(&paths) {
        return Err(ServiceError::usage(format!(
            "{} is not valid, not restarting: {e}",
            paths.config.display()
        )));
    }
    systemctl(&["restart", SERVICE_NAME])?;
    out.line(format!("{SERVICE_NAME}: {}", active_state(SERVICE_NAME)));
    Ok(())
}

pub fn status(out: &mut Report) -> Result<(), ServiceError> {
    require_systemd()?;
    let paths = service_paths();
    if !paths.unit.exists() {
        out.line(format!(
            "{SERVICE_NAME}: not installed ({} missing)",
            paths.unit.display()
        ));
        return Ok(());
    }
    out.line(status_text(SERVICE_NAME)?);
    match installed_config(&paths) {
        Ok(r) => report_state(out, &r),
        Err(e) => out.line(format!(
            "settings    not readable ({e}); run `sudo nettest-client service status`"
        )),
    }
    Ok(())
}

pub fn run_as_service(_: PathBuf) -> ExitCode {
    eprintln!(
        "'service run' is the Windows service entry point; systemd runs `nettest-client monitor` directly"
    );
    ExitCode::from(super::EXIT_USAGE)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn monitor_unit() {
        let paths = service_paths();
        let u = unit_text(std::path::Path::new("/usr/local/bin/nettest-client"), &paths);
        assert!(u.contains("LoadCredential=monitor.toml:/etc/nettest/monitor.toml\n"));
        assert!(u.contains("ExecStart=/usr/local/bin/nettest-client monitor --config %d/monitor.toml --log-file /var/log/nettest-monitor/monitor.log\n"));
        assert!(u.contains("LogsDirectory=nettest-monitor\n"));
        assert!(!u.contains("StateDirectory"));
        assert!(u.contains("AmbientCapabilities=CAP_NET_RAW\nCapabilityBoundingSet=CAP_NET_RAW\n"));
        assert!(u.contains("RestartSec=5\n"));
    }
}
