//! systemd unit rendering. Pure so it is unit tested on every host.
//!
//! Hardening choices: `DynamicUser=yes` gives the service a throwaway UID with no home and no
//! shell; `StateDirectory`/`LogsDirectory` create the service's directories owned by that user
//! (each DynamicUser unit needs its *own* `LogsDirectory` name: systemd re-chowns it on every
//! start). The config stays root-only and reaches the service as a *credential*: systemd copies
//! it into `$CREDENTIALS_DIRECTORY` with the service user as owner, which `ConfigurationDirectory=`
//! alone would not do for a dynamic user. `LoadCredential=` needs systemd 247 (2020) or newer.

use std::path::{Path, PathBuf};

pub struct UnitSpec<'a> {
    /// Comment lines at the top of the file (without the leading `# `).
    pub header: &'a [&'a str],
    pub description: &'a str,
    /// `Documentation=` value, e.g. `man:nettest-server`.
    pub documentation: &'a str,
    /// Everything after `ExecStart=`. `%d` is the credentials directory.
    pub exec_start: &'a str,
    /// `(credential name, source path)` for `LoadCredential=`.
    pub credential: (&'a str, &'a Path),
    pub state_dir: Option<&'a str>,
    pub logs_dir: &'a str,
    pub restart_sec: u32,
    /// Ambient capabilities to grant; empty means an empty bounding set.
    pub capabilities: &'a [&'a str],
}

pub fn render_unit(p: &UnitSpec<'_>) -> String {
    let mut out = String::with_capacity(1024);
    for h in p.header {
        out.push_str("# ");
        out.push_str(h);
        out.push('\n');
    }
    out.push_str("[Unit]\n");
    out.push_str(&format!("Description={}\n", p.description));
    out.push_str(&format!("Documentation={}\n", p.documentation));
    out.push_str("After=network-online.target\nWants=network-online.target\n\n");
    out.push_str("[Service]\nType=simple\nDynamicUser=yes\n");
    if let Some(s) = p.state_dir {
        out.push_str(&format!("StateDirectory={s}\n"));
    }
    out.push_str(&format!("LogsDirectory={}\n", p.logs_dir));
    out.push_str(&format!(
        "LoadCredential={}:{}\n",
        p.credential.0,
        p.credential.1.display()
    ));
    out.push_str(&format!("ExecStart={}\n", p.exec_start));
    out.push_str(&format!(
        "Restart=on-failure\nRestartSec={}\nNoNewPrivileges=yes\nProtectSystem=strict\nProtectHome=yes\nPrivateTmp=yes\n",
        p.restart_sec
    ));
    if p.capabilities.is_empty() {
        out.push_str("CapabilityBoundingSet=\n");
    } else {
        let caps = p.capabilities.join(" ");
        out.push_str(&format!(
            "AmbientCapabilities={caps}\nCapabilityBoundingSet={caps}\n"
        ));
    }
    out.push_str("\n[Install]\nWantedBy=multi-user.target\n");
    out
}

/// The executable named by an existing unit's `ExecStart=` line.
pub fn exec_from_unit(text: &str) -> Option<PathBuf> {
    text.lines()
        .find_map(|l| l.strip_prefix("ExecStart="))
        .and_then(|rest| rest.split_whitespace().next())
        .map(|p| Path::new(p).to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The server's unit must come out exactly as the pre-refactor renderer produced it.
    #[test]
    fn server_unit_is_byte_identical() {
        let config = PathBuf::from("/etc/nettest/server.toml");
        let spec = UnitSpec {
            header: &[
                "Generated by `nettest-server service install`. Edit settings with",
                "`nettest-server service edit ...`, not by hand: install/edit rewrite this file.",
            ],
            description: "nettest network troubleshooting server (echo, soak and throughput for nettest-client)",
            documentation: "man:nettest-server",
            exec_start: "/usr/local/bin/nettest-server --no-tui --config %d/server.toml",
            credential: ("server.toml", &config),
            state_dir: Some("nettest"),
            logs_dir: "nettest",
            restart_sec: 2,
            capabilities: &[],
        };
        let expected = "# Generated by `nettest-server service install`. Edit settings with\n\
# `nettest-server service edit ...`, not by hand: install/edit rewrite this file.\n\
[Unit]\n\
Description=nettest network troubleshooting server (echo, soak and throughput for nettest-client)\n\
Documentation=man:nettest-server\n\
After=network-online.target\n\
Wants=network-online.target\n\
\n\
[Service]\n\
Type=simple\n\
DynamicUser=yes\n\
StateDirectory=nettest\n\
LogsDirectory=nettest\n\
LoadCredential=server.toml:/etc/nettest/server.toml\n\
ExecStart=/usr/local/bin/nettest-server --no-tui --config %d/server.toml\n\
Restart=on-failure\n\
RestartSec=2\n\
NoNewPrivileges=yes\n\
ProtectSystem=strict\n\
ProtectHome=yes\n\
PrivateTmp=yes\n\
CapabilityBoundingSet=\n\
\n\
[Install]\n\
WantedBy=multi-user.target\n";
        assert_eq!(render_unit(&spec), expected);
        let low = render_unit(&UnitSpec {
            capabilities: &["CAP_NET_BIND_SERVICE"],
            ..spec
        });
        assert!(low.contains(
            "PrivateTmp=yes\nAmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE\n\n[Install]"
        ));
        assert_eq!(
            exec_from_unit(&low).unwrap(),
            PathBuf::from("/usr/local/bin/nettest-server")
        );
    }

    #[test]
    fn optional_state_dir_and_multiple_caps() {
        let config = PathBuf::from("/etc/nettest/monitor.toml");
        let u = render_unit(&UnitSpec {
            header: &[],
            description: "d",
            documentation: "man:x",
            exec_start: "/x monitor",
            credential: ("monitor.toml", &config),
            state_dir: None,
            logs_dir: "nettest-monitor",
            restart_sec: 5,
            capabilities: &["CAP_NET_RAW", "CAP_NET_BIND_SERVICE"],
        });
        assert!(u.starts_with("[Unit]\n"));
        assert!(!u.contains("StateDirectory"));
        assert!(u.contains("LogsDirectory=nettest-monitor\n"));
        assert!(u.contains("AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE\n"));
        assert!(u.contains("RestartSec=5\n"));
    }
}
