//! The server's systemd unit: parameters on top of `nettest_service::systemd::render_unit`.
//! `StateDirectory=nettest` holds the generated certificate; the unit grants
//! CAP_NET_BIND_SERVICE only when a listener sits below port 1024.

use std::path::PathBuf;

use nettest_service::systemd::UnitSpec;
#[cfg_attr(not(target_os = "linux"), allow(unused_imports))]
pub use nettest_service::systemd::exec_from_unit;

pub struct UnitParams {
    pub exec: PathBuf,
    pub config: PathBuf,
    /// Any listener on a port below 1024.
    pub needs_low_port: bool,
}

pub fn render_unit(p: &UnitParams) -> String {
    let exec_start = format!("{} --no-tui --config %d/server.toml", p.exec.display());
    nettest_service::systemd::render_unit(&UnitSpec {
        header: &[
            "Generated by `nettest-server service install`. Edit settings with",
            "`nettest-server service edit ...`, not by hand: install/edit rewrite this file.",
        ],
        description: super::DESCRIPTION,
        documentation: "man:nettest-server",
        exec_start: &exec_start,
        credential: ("server.toml", &p.config),
        state_dir: Some("nettest"),
        logs_dir: "nettest",
        restart_sec: 2,
        capabilities: if p.needs_low_port {
            &["CAP_NET_BIND_SERVICE"]
        } else {
            &[]
        },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_contents() {
        let p = UnitParams {
            exec: "/usr/local/bin/nettest-server".into(),
            config: "/etc/nettest/server.toml".into(),
            needs_low_port: false,
        };
        let u = render_unit(&p);
        assert!(u.contains("LoadCredential=server.toml:/etc/nettest/server.toml"));
        assert!(
            u.contains("ExecStart=/usr/local/bin/nettest-server --no-tui --config %d/server.toml")
        );
        assert!(u.contains("DynamicUser=yes"));
        assert!(!u.contains("AmbientCapabilities"));
        assert_eq!(
            exec_from_unit(&u).unwrap(),
            PathBuf::from("/usr/local/bin/nettest-server")
        );
        let low = render_unit(&UnitParams {
            needs_low_port: true,
            ..p
        });
        assert!(low.contains("AmbientCapabilities=CAP_NET_BIND_SERVICE"));
    }
}
