//! systemd unit rendering. Pure so it is unit tested on every host.
//!
//! Hardening choices: `DynamicUser=yes` gives the service a throwaway UID with no home and no
//! shell; `StateDirectory`/`LogsDirectory` create `/var/lib/nettest` and `/var/log/nettest`
//! owned by that user. The config (which holds the token) stays root-only at `/etc/nettest` and
//! reaches the service as a *credential*: systemd copies it into `$CREDENTIALS_DIRECTORY` with
//! the service user as owner, which `ConfigurationDirectory=` alone would not do for a dynamic
//! user. `LoadCredential=` needs systemd 247 (2020) or newer.

use std::path::{Path, PathBuf};

pub struct UnitParams {
    pub exec: PathBuf,
    pub config: PathBuf,
    /// Any listener on a port below 1024.
    pub needs_low_port: bool,
}

pub fn render_unit(p: &UnitParams) -> String {
    let caps = if p.needs_low_port {
        "AmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE\n"
    } else {
        "CapabilityBoundingSet=\n"
    };
    format!(
        "# Generated by `nettest-server service install`. Edit settings with\n\
         # `nettest-server service edit ...`, not by hand: install/edit rewrite this file.\n\
         [Unit]\n\
         Description={desc}\n\
         Documentation=man:nettest-server\n\
         After=network-online.target\n\
         Wants=network-online.target\n\
         \n\
         [Service]\n\
         Type=simple\n\
         DynamicUser=yes\n\
         StateDirectory=nettest\n\
         LogsDirectory=nettest\n\
         LoadCredential=server.toml:{config}\n\
         ExecStart={exec} --no-tui --config %d/server.toml\n\
         Restart=on-failure\n\
         RestartSec=2\n\
         NoNewPrivileges=yes\n\
         ProtectSystem=strict\n\
         ProtectHome=yes\n\
         PrivateTmp=yes\n\
         {caps}\
         \n\
         [Install]\n\
         WantedBy=multi-user.target\n",
        desc = super::DESCRIPTION,
        config = p.config.display(),
        exec = p.exec.display(),
    )
}

/// The executable named by an existing unit's `ExecStart=` line.
pub fn exec_from_unit(text: &str) -> Option<PathBuf> {
    text.lines()
        .find_map(|l| l.strip_prefix("ExecStart="))
        .and_then(|rest| rest.split_whitespace().next())
        .map(|p| Path::new(p).to_path_buf())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn unit_contents() {
        let p = UnitParams {
            exec: "/usr/local/bin/nettest-server".into(),
            config: "/etc/nettest/server.toml".into(),
            needs_low_port: false,
        };
        let u = render_unit(&p);
        assert!(u.contains("LoadCredential=server.toml:/etc/nettest/server.toml"));
        assert!(
            u.contains("ExecStart=/usr/local/bin/nettest-server --no-tui --config %d/server.toml")
        );
        assert!(u.contains("DynamicUser=yes"));
        assert!(!u.contains("AmbientCapabilities"));
        assert_eq!(
            exec_from_unit(&u).unwrap(),
            PathBuf::from("/usr/local/bin/nettest-server")
        );
        let low = render_unit(&UnitParams {
            needs_low_port: true,
            ..p
        });
        assert!(low.contains("AmbientCapabilities=CAP_NET_BIND_SERVICE"));
    }
}
